on: push
name: lint

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v4
              with:
                  clean: false

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Install deps
              run: pnpm i

            - name: Run ESLint
              run: pnpm lint
              env:
                  CI: true
